name: Build and Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y lcov gcovr cmake g++ clang make

      - name: Build with coverage
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
          cmake --build build

      - name: Run tests
        run: |
          cd build && ctest

      - name: Generate lcov report
        run: |
          lcov --capture --directory build --output-file coverage.info --ignore-errors mismatch
          lcov --list coverage.info # <--- Теперь твои исходники будут тут!

      - name: Filter out external and test coverage
        run: |
          lcov --remove coverage.info '*/_deps/*' '*/deps/*' '*/third_party/*' '*/googletest/*' '*/gtest/*' '*/tests/*' '*/test/*' '/usr/*' -o coverage_filtered.info
          lcov --list coverage_filtered.info

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage_filtered.info